package com.putraworks.graveatlas.data.model;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

/**
 * A notification generated by the system or alert rules.
 * Created via POST /api/notifications, retrieved via GET /api/notifications
 */
public class Notification {
    public String id;
    public String type;        // anomaly_detected, confidence_drop, source_dead, duplicate_found,
                               // review_needed, lock_expiring, task_assigned, task_completed,
                               // task_rejected, merge_available, fix_available, data_loss, new_record, custom
    public String severity;    // info, warning, critical
    public String title;
    public String message;
    public String recordId;
    public String cemeteryId;
    public JSONObject metadata;
    public String recipient;
    public boolean read;
    public boolean dismissed;
    public String createdAt;
    public String readAt;
    public String dismissedAt;

    public static Notification fromJson(JSONObject json) {
        Notification result = new Notification();
        result.id = json.optString("id", "");
        result.type = json.optString("type", "");
        result.severity = json.optString("severity", "info");
        result.title = json.optString("title", "");
        result.message = json.optString("message", "");
        result.recordId = json.optString("recordId", null);
        result.cemeteryId = json.optString("cemeteryId", null);
        result.metadata = json.optJSONObject("metadata");
        result.recipient = json.optString("recipient", "all");
        result.read = json.optBoolean("read", false);
        result.dismissed = json.optBoolean("dismissed", false);
        result.createdAt = json.optString("createdAt", null);
        result.readAt = json.optString("readAt", null);
        result.dismissedAt = json.optString("dismissedAt", null);
        return result;
    }

    public boolean isCritical() { return "critical".equals(severity); }
    public boolean isWarning() { return "warning".equals(severity); }
    public boolean isUnread() { return !read && !dismissed; }

    public String getSeverityIcon() {
        switch (severity) {
            case "critical": return "🔴";
            case "warning": return "🟡";
            case "info": return "🔵";
            default: return "⚪";
        }
    }

    public String getTypeIcon() {
        switch (type) {
            case "anomaly_detected": return "⚠️";
            case "confidence_drop": return "📉";
            case "source_dead": return "🔗";
            case "duplicate_found": return "📋";
            case "review_needed": return "🔍";
            case "lock_expiring": return "⏰";
            case "task_assigned": return "📌";
            case "task_completed": return "✅";
            case "task_rejected": return "❌";
            case "merge_available": return "🔗";
            case "fix_available": return "🔧";
            case "data_loss": return "🚨";
            case "new_record": return "✨";
            case "custom": return "📢";
            default: return "🔔";
        }
    }

    public String getSummaryLine() {
        return String.format("%s %s %s", getSeverityIcon(), getTypeIcon(), title);
    }
}
